defaults:
  run:
    working-directory: ts-frontend

name: Build
on: [push]
jobs:
  build:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
        working-directory: ts-frontend
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
